import Head from 'next/head'
import Image from 'next/legacy/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'
import placeholder from '../../public/assets/article.png'
import Link from 'next/link'
// import { SERVER_URL } from '@/utils/const'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [articles, setArticles] = useState(null);

  useEffect(() => {
    const fetchArticles = async () => {
      try{
        const articles = await axios.get("http://13.53.142.82:5500/articles")
        setArticles(articles.data)
      }catch(err){
        console.log(err)
      }
    }
    fetchArticles()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.classes}`}>
        <section>
          <div className={styles.head}>Previous Shows</div>
          <div className={styles.articleContainer}>
            {articles?.length > 0 ? (
              articles.map(article => (
                <div key={article.id} className={styles.article}>
                <div className={styles.articleImg}>
                  <Link href={`/articles/${article.id}`}>
                    <Image src={article.image.startsWith("localhost") ? placeholder : article.image} width={400} height={600} alt="article-image" />
                  </Link>
                </div>
              </div>
              ))
            ) : (
              <div>No articles found</div>
            )}
          </div>
        </section>
      </main>
    </>
  )
}
