import Head from 'next/head'
import Image from 'next/legacy/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'
import placeholder from '../../public/assets/article.png'
import banner from '../../public/assets/mountains.avif'
import Link from 'next/link'
// import { SERVER_URL } from '@/utils/const'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [articles, setArticles] = useState(null);

  useEffect(() => {
    const fetchArticles = async () => {
      try {
        const articles = await axios.get("http://13.53.142.82:5500/articles")
        setArticles(articles.data)
      } catch (err) {
        console.log(err)
      }
    }
    fetchArticles()
  }, [])

  return (
    <>
      <Head>
        <title>The Big Mouth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.classes}`}>
        <section className={styles.hero}>
          <div className={styles.img}></div>
          <div className={styles.heroContent}>
            <p className={styles.category}>Booking Now...</p>
            <h1>No Man's Island</h1>
            <p className={styles.heroDes}>Deserunt esse commodo commodo enim consequat non magna. Labore ipsum aute nulla ex pariatur nisi laboris incididunt magna aliqua id eu duis ad. Tempor eiusmod ex proident laborum exercitation nulla mollit veniam aliquip.</p>
            <a className={styles.cta}>Read More</a>
          </div>
        </section>
        <section>
          <div className={styles.head}>Previous Shows</div>
          <div className={styles.articleContainer}>
            {articles?.length > 0 ? (
              articles.map(article => (
                <div key={article.id} className={styles.article}>
                  <div className={styles.articleImg}>
                    <Link href={`/articles/${article.id}`}>
                      <Image src={article.image.startsWith("localhost") ? placeholder : article.image} width={400} height={600} alt="article-image" />
                    </Link>
                  </div>
                </div>
              ))
            ) : (
              <div>No articles found</div>
            )}
          </div>
        </section>
      </main>
    </>
  )
}
